src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenoms = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: News::class)]
    private Collection $news;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class)]
    private Collection $comments;

    public function __construct()
    {
        $this->news = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenoms(): ?string
    {
        return $this->Prenoms;
    }

    public function setPrenoms(string $Prenoms): self
    {
        $this->Prenoms = $Prenoms;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, News>
     */
    public function getNews(): Collection
    {
        return $this->news;
    }

    public function addNews(News $news): self
    {
        if (!$this->news->contains($news)) {
            $this->news->add($news);
            $news->setAuthor($this);
        }

        return $this;
    }

    public function removeNews(News $news): self
    {
        if ($this->news->removeElement($news)) {
            // set the owning side to null (unless already changed)
            if ($news->getAuthor() === $this) {
                $news->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}
 

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\User;
use App\Repository\CommentRepository;
use Knp\Component\Pager\PaginatorInterface; 
use App\Form\CommentType;
use App\Repository\CategoryRepository;
use App\Repository\NewsRepository;
use App\Service\NavCategory;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class AccueilController extends AbstractController
{
    private $navCategory;
    

    public function __construct(NavCategory $navCategory)
    {
        $this->navCategory = $navCategory;
    }

    #[Route('/', name: 'app_accueil')]
    public function index(NewsRepository $newsRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $newsRepository->paginationQuery(),
            $request->query->get('page', 1),
            8
        );

        return $this->render('accueil/index.html.twig',[
            'categoryList' => $this->navCategory->category(),
            'pagination' => $pagination
        ]);
    }

    #[Route('/news/{id<[0-9]+>}', name: 'app_new_show')]
    public function newsShow($id, NewsRepository $newsRepository,Request $request, EntityManagerInterface $entityManager, CommentRepository $commentRepository):Response
    {
        $newsId = $newsRepository->find($id);

        $comment = new Comment();
        $form = $this->createForm(CommentType::class,$comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $user = $this->getUser();
            $comment->setAuthor($user);
            $comment->setNews($newsId);
            $comment->setCreatedAt(new \dateTime);
            $entityManager->persist($comment);
            $entityManager->flush();
            $this->addFlash('success','Votre commentaire a été envoyé');
        }

        
        return $this->render('accueil/news_single.html.twig',[
            'single_news'=>$newsRepository->find($newsId),
            'categoryList' => $this->navCategory->category(),
            'form'=>$form->createView(),
            'comments'=>$commentRepository->findBy(['news'=>$newsId])
        ]);
    }

    #[Route('/news/{id<[0-9]+>}/category', name: 'app_new_by_category_show')]
    public function NewsBysCategory($id,NewsRepository $newsRepository, CategoryRepository $categoryRepository):Response
    {
        $idCategory = $categoryRepository->find($id);
        $categoryName= $categoryRepository->findOneBy(['id'=>$id],[]);
        
        $newsByCategory = $newsRepository->findBy(['category'=>$idCategory],[]);

        return $this->render('accueil/newsByCategory.html.twig',[
            'news'=>$newsByCategory,
            'categoryList' => $this->navCategory->category(),
            'category'=>$categoryName
        ]);
    }
}

templates/accueil/index.html.twig
{% extends 'Layout/base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}
        <div class="site-section ">
        <div class="container "> 
        <div id="carouselExampleIndicators" class="carousel slide">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-l	abel="Slide 1">
            </button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2">
            </button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{asset('assets/images/afterheaderca (2).png') }}" class="d-block w-100 h-30 img-fluid rounded" alt="...">
            </div>
            <div class="carousel-item">
              <img src="{{asset('assets/images/afterheaderca (2).png') }}" class="d-block w-100 h-30 img-fluid rounded" alt="...">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" ariahidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div> <br>
  
        <div class="row mb-5">
          <div class="col-12">
            <h2 class="text-center">NOS RECENTS ARTICLES</h2>
          </div>
        </div>
        <div class="row">
          {% for news in pagination %}
            <div class="col-lg-3 mb-3">
            <div class="entry2 bg-light">
              <a href="{{ path('app_new_show',{'id': news.id}) }}">
              <img class="img-fluid rounded" src="{{ vich_uploader_asset( news,'imageFile')}}">
              </a>
              <div class="excerpt" >
              <span class="post-category text-white bg-success mb-3">{{ news.category }}</span>

              <h2><a href="{{ path('app_new_show',{'id': news.id}) }}">{{ news.title }}</a></h2>
              <div class="post-meta align-items-center text-left clearfix">
                <!--<figure class="author-figure mb-0 mr-3 float-left">
                  <img src="public/images/BgEtudiantB.png" alt="Image" class="img-fluid">
                </figure>-->
                <span class="d-inline-block mt-1">By <a href="#"><b>{{ news.author.nom }} {{ news.author.prenoms }}</b></a></span>
                <span>{{ news.createdAt |ago}}</span>
              </div>
              
                <p>{{ news.description|slice(0,25) }}...</p>
                <p><a href="{{ path('app_new_show',{'id': news.id}) }}">Lire plus...</a></p>
              </div>
          </div>
          </div>
          {% endfor %}
          
          </div> <br>
          {{ knp_pagination_render(pagination) }}

      </div>
    </div>

{% endblock %}

templates/accueil/newsByCategory.html.twig
{% extends 'Layout/base.html.twig' %}

{% block title %}{{ category.name }}{% endblock %}

{% block body %}
      <div class="site-section">
          <div class="container">
        <div class="row mb-5">
          <div class="col-12">
            <h2>{{ category.name }} category</h2>
            {% if news|length<1 %}
                <p>Aucune news pour cette catégorie</p>
            {% endif %}
          </div>
        </div>
        <div class="row">
          {% for news in news %}
          <div class="col-lg-3 mb-3">
            <div class="entry2">
              <a href="{{ path('app_new_show',{'id': news.id}) }}">
              <img class="img-fluid rounded" src="{{ vich_uploader_asset( news,'imageFile')}}">
              <!--<img src="images/img_2.jpg" alt="Image" class="img-fluid rounded">-->
              </a>
              <div class="excerpt">
              <span class="post-category text-white bg-success mb-3">{{ news.category }}</span>

              <h2><a href="{{ path('app_new_show',{'id': news.id}) }}">{{ news.title }}</a></h2>
              <div class="post-meta align-items-center text-left clearfix">
                <!--<figure class="author-figure mb-0 mr-3 float-left">
                  <img src="images/person_1.jpg" alt="Image" class="img-fluid">
                </figure> -->
                <span class="d-inline-block mt-1">By <a href="#"> <b>{{ news.author.nom }} {{ news.author.prenoms }} </b></a></span>
                <span>{{ news.createdAt |ago}}</span>
              </div>
              
                <p>{{ news.description|slice(0,30) }}...</p>
                <p><a href="{{ path('app_new_show',{'id': news.id}) }}">Lire plus...</a></p>
              </div>
          </div>
          </div>
          {% endfor %}
          
          </div>

      </div>
    </div>

{% endblock %}

templates/accueil/news_single.html.twig
{% extends 'Layout/base.html.twig' %}
{% block title %}{{ single_news.Title }}{% endblock %}
{% block body %}
<section class="site-section py-lg">
      <div class="container">
        
        <div class="row blog-entries element-animate">

          <div class="col-md-12 col-lg-8 main-content">
            
            <div class="post-content-body">
                <img style="width:100%" class="img-fluid rounded" src="{{ vich_uploader_asset(single_news, 'imageFile') }}">
                <h1>{{ single_news.title }}</h1>
                <label>Description</label>
                <p>{{ single_news.description}}</p>  
            


               <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Laisser un commentaire</h3>
                {% if app.user%}

                  {{ form_start (form)}}
                    <label>Commentaires</label>
                    {{ form_widget(form.content,{'attr':{'class':'form form-control','placeholder':'Ecrivez votre commentaire'}}) }}<br><br>
                    <input type="submit" value="Envoyer" class="btn btn-primary">
                  {{ form_end(form) }}

                  {% else %}
                  Vous devez vous connecter pour pouvoir laisser un commentaire - <a href="{{ path('app_login') }}">Se connecter</a>

                {% endif %} <br>
                  <ul class="comment-list">
                  {% for comment in comments %}
                      <li class="comment">
                        <div class="comment-body">
                          <h3>{{ comment.author.nom }} {{ comment.author.prenoms }}</h3>
                          <div class="meta">{{ comment.createdAt|ago }}</div>
                          <p>{{ comment.content }}</p>
                          <p><a href="#" class="reply rounded">Répondre</a></p>
                        </div>
                      </li>
                  {% endfor %} 
                  </ul> 

            </div>

          </div> 

            <!--



            <div class="pt-5">
              <h3 class="mb-5">6 Comments</h3>
              <ul class="comment-list">
                <li class="comment">
                  <div class="vcard">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>Jean Doe</h3>
                    <div class="meta">January 9, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply rounded">Reply</a></p>
                  </div>
                </li>

                <li class="comment">
                  <div class="vcard">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>Jean Doe</h3>
                    <div class="meta">January 9, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply rounded">Reply</a></p>
                  </div>

                  <ul class="children">
                    <li class="comment">
                      <div class="vcard">
                        <img src="images/person_1.jpg" alt="Image placeholder">
                      </div>
                      <div class="comment-body">
                        <h3>Jean Doe</h3>
                        <div class="meta">January 9, 2018 at 2:21pm</div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                        <p><a href="#" class="reply rounded">Reply</a></p>
                      </div>


                      <ul class="children">
                        <li class="comment">
                          <div class="vcard">
                            <img src="images/person_1.jpg" alt="Image placeholder">
                          </div>
                          <div class="comment-body">
                            <h3>Jean Doe</h3>
                            <div class="meta">January 9, 2018 at 2:21pm</div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                            <p><a href="#" class="reply rounded">Reply</a></p>
                          </div>

                            <ul class="children">
                              <li class="comment">
                                <div class="vcard">
                                  <img src="images/person_1.jpg" alt="Image placeholder">
                                </div>
                                <div class="comment-body">
                                  <h3>Jean Doe</h3>
                                  <div class="meta">January 9, 2018 at 2:21pm</div>
                                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                  <p><a href="#" class="reply rounded">Reply</a></p>
                                </div>
                              </li>
                            </ul>
                        </li>
                      </ul>
                    </li>
                  </ul>
                </li>

                <li class="comment">
                  <div class="vcard">
                    <img src="images/person_1.jpg" alt="Image placeholder">
                  </div>
                  <div class="comment-body">
                    <h3>Jean Doe</h3>
                    <div class="meta">January 9, 2018 at 2:21pm</div>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                    <p><a href="#" class="reply rounded">Reply</a></p>
                  </div>
                </li>
              </ul>
              
            -->
          </div>

          <!-- END main-content -->

          <div class="col-md-12 col-lg-4 sidebar">
            <div class="sidebar-box search-form-wrap">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon fa fa-search"></span>
                  <input type="text" class="form-control" id="s" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <!-- END sidebar-box -->
            
            <div class="sidebar-box">
              <h3 class="heading">Articles populaires</h3>
              <div class="post-entry-sidebar">
                <ul>
                  <li>
                    <a href="">
                      <img src="{{asset('assets/images/img_1.jpg') }}" alt="Image placeholder" class="mr-4">
                      <div class="text">
                        <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                        <div class="post-meta">
                          <span class="mr-2">March 15, 2018 </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <img src="images/img_2.jpg" alt="Image placeholder" class="mr-4">
                      <div class="text">
                        <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                        <div class="post-meta">
                          <span class="mr-2">March 15, 2018 </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="">
                      <img src="images/img_3.jpg" alt="Image placeholder" class="mr-4">
                      <div class="text">
                        <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                        <div class="post-meta">
                          <span class="mr-2">March 15, 2018 </span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <!-- END sidebar-box -->

            <div class="sidebar-box">
              <h3 class="heading">Categories</h3>
              <ul class="categories">
                {% for link in categoryList %}
                  <li><a href="{{ path('app_new_by_category_show',{'id':link.id}) }}">{{ link.name}}</a></li>
                {% endfor %}
              </ul>
            </div>
            <!-- END sidebar-box -->
          </div>
          <!-- END sidebar -->

        </div>
      </div>
    </section>
{% endblock %}